# Generated by Django 4.2.2 on 2024-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
