# Generated by Django 4.2.2 on 2024-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slag_blog",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="slag"
            ),
        ),
    ]
