# Generated by Django 4.2.2 on 2024-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_slag_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="slag_blog",
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="slug"
            ),
        ),
    ]
