# Generated by Django 4.2.2 on 2024-07-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="Укажите периодичность рассылки",
                        max_length=150,
                        verbose_name="Периодичность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Периодичность рассылки",
                "verbose_name_plural": "Периодичности рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=100, verbose_name="Статус рассылки"),
                ),
            ],
            options={
                "verbose_name": "Статус рассылки",
                "verbose_name_plural": "Статусы рассылки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="enable",
            field=models.BooleanField(default=False, verbose_name="Активность"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_and_time",
            field=models.DateTimeField(verbose_name="Дата и время первой отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to="coursework.mailingfrequency",
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to="coursework.mailingstatus",
                verbose_name="Статус",
            ),
        ),
    ]
