# Generated by Django 4.2.2 on 2024-07-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0002_mailingfrequency_mailingstatus_mailing_enable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="client",
            field=models.ManyToManyField(
                help_text="Выберите клиентов. (Для отмены зажмите CTRL и выберите клиента",
                related_name="mailing",
                to="coursework.client",
                verbose_name="Клиенты",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_and_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.ForeignKey(
                help_text="Выберите периодичность",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to="coursework.mailingfrequency",
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете сообщения для отправки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailing",
                to="coursework.message",
                verbose_name="Сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to="coursework.mailingstatus",
                verbose_name="Статус",
            ),
        ),
    ]
