# Generated by Django 4.2.2 on 2024-07-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coursework",
            "0003_alter_mailing_client_alter_mailing_date_and_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="date_and_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время попытки отправки"
            ),
        ),
    ]
