# Generated by Django 4.2.2 on 2024-07-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0004_attempt_date_and_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "Может отключать рассылки")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
