# Generated by Django 4.2.2 on 2024-07-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coursework", "0005_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь создавший",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailing",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь создавший",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь создавший",
            ),
        ),
    ]
