# Generated by Django 4.2.2 on 2024-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_blocking", "Может заблокировать пользователя")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocking",
            field=models.BooleanField(default=False, verbose_name="Статус блокировки"),
        ),
    ]
